ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}-bullseye

WORKDIR /pipelinewise

COPY ./setup.py ./README.md ./

RUN pip install -U pip setuptools wheel && \
    pip install -Ue .[test]

WORKDIR /app

VOLUME /app
