services:
  db_primary:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${TAP_POSTGRES_TEST_PRIMARY_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: my-secret-passwd
      POSTGRES_DB: tap_postgres_test
    command: [postgres, -c, config_file=/etc/postgresql/postgresql.conf]
    volumes:
      - ./db_setup/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./db_setup/initialize-primary.sh:/docker-entrypoint-initdb.d/initialize-primary.sh:ro
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -h 127.0.0.1 -U postgres -d tap_postgres_test && test -f "$${PGDATA}/primary_ready"']
      interval: 2s
      timeout: 5s
      retries: 60

  db_replica:
    image: postgres:14-bookworm
    ports:
      - "${TAP_POSTGRES_TEST_SECONDARY_PORT:-5433}:5432"
    depends_on:
      db_primary:
        condition: service_healthy
    environment:
      PGPASSWORD: repl_password
    entrypoint: [bash, /initialize-replica.sh]
    volumes:
      - ./db_setup/initialize-replica.sh:/initialize-replica.sh:ro
      - ./db_setup/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U repl_user -d tap_postgres_test']
      interval: 2s
      timeout: 5s
      retries: 60
