SAMPLE_OUTPUT_FROM_SF = [
            {
                'table_name': 'BAR_TABLE',
                'schema_name': 'FOO_SCHEMA',
                'column_name': 'FOO_COLUMN_1',
                'data_type': '{"type":"FIXED","precision":38,"scale":0,"nullable":true}',
                'null?': 'true',
                'default': '',
                'kind': 'COLUMN',
                'expression': '',
                'comment': '',
                'database_name': 'FOO_DB',
                'autoincrement': ''
            },
            {
                'table_name': 'BAR_TABLE',
                'schema_name': 'FOO_SCHEMA',
                'column_name': 'FOO_COLUMN_2',
                'data_type': '{"type":"TEXT","length":16777216,"byteLength":16777216,"nullable":true,"fixed":false}',
                'null?': 'true',
                'default': '',
                'kind': 'COLUMN',
                'expression': '',
                'comment': '',
                'database_name': 'FOO_DB',
                'autoincrement': ''
            },
            {
                'table_name': 'BAR_TABLE',
                'schema_name': 'FOO_SCHEMA',
                'column_name': 'FOO_COLUMN_3',
                'data_type': '{"type":"TEXT","length":16777216,"byteLength":16777216,"nullable":true,"fixed":false}',
                'null?': 'true',
                'default': '',
                'kind': 'COLUMN',
                'expression': '',
                'comment': '',
                'database_name': 'FOO_DB',
                'autoincrement': ''
            },

            {
                'table_name': 'BAR_TABLE',
                'schema_name': 'FOO_SCHEMA',
                'column_name': 'FOO_COLUMN_4',
                'data_type': '{"type":"NUMBER","nullable":false,"fixed":false}',
                'null?': 'true',
                'default': '',
                'kind': 'COLUMN',
                'expression': '',
                'comment': '',
                'database_name': 'FOO_DB',
                'autoincrement': ''
            },
            {
                'table_name': 'BAR_TABLE',
                'schema_name': 'FOO_SCHEMA',
                'column_name': '_SDC_EXTRACTED_AT',
                'data_type': '{"type":"TIMESTAMP_NTZ","nullable":false,"fixed":false}',
                'null?': 'true',
                'default': '',
                'kind': 'COLUMN',
                'expression': '',
                'comment': '',
                'database_name': 'FOO_DB',
                'autoincrement': ''
            },
            {
                'table_name': 'BAR_TABLE',
                'schema_name': 'FOO_SCHEMA',
                'column_name': '_SDC_BATCHED_AT',
                'data_type': '{"type":"TIMESTAMP_NTZ","nullable":false,"fixed":false}',
                'null?': 'true',
                'default': '',
                'kind': 'COLUMN',
                'expression': '',
                'comment': '',
                'database_name': 'FOO_DB',
                'autoincrement': ''
            },
            {
                'table_name': 'BAR_TABLE',
                'schema_name': 'FOO_SCHEMA',
                'column_name': '_SDC_DELETED_AT',
                'data_type': '{"type":"TIMESTAMP_NTZ","nullable":false,"fixed":false}',
                'null?': 'true',
                'default': '',
                'kind': 'COLUMN',
                'expression': '',
                'comment': '',
                'database_name': 'FOO_DB',
                'autoincrement': ''
            },
            {
                'table_name': 'BAR_TABLE',
                'schema_name': 'FOO_SCHEMA',
                'column_name': '_SDC_FOO_BAR',
                'data_type': '{"type":"TIMESTAMP_NTZ","nullable":false,"fixed":false}',
                'null?': 'true',
                'default': '',
                'kind': 'COLUMN',
                'expression': '',
                'comment': '',
                'database_name': 'FOO_DB',
                'autoincrement': ''
            },
        ]
