export const LOAD_TARGETS = 'ETLWise/App/LOAD_TARGETS';
export const LOAD_TARGETS_SUCCESS = 'ETLWise/App/LOAD_TARGETS_SUCCESS';
export const LOAD_TARGETS_ERROR = 'ETLWise/App/LOAD_TARGETS_ERROR';

export const LOAD_TARGET = 'ETLWise/App/LOAD_TARGET';
export const LOAD_TARGET_SUCCESS = 'ETLWise/App/LOAD_TARGET_SUCCESS';
export const LOAD_TARGET_ERROR = 'ETLWise/App/LOAD_TARGET_ERROR';

export const LOAD_TAPS = 'ETLWise/App/LOAD_TAPS';
export const LOAD_TAPS_SUCCESS = 'ETLWise/App/LOAD_TAPS_SUCCESS';
export const LOAD_TAPS_ERROR = 'ETLWise/App/LOAD_TAPS_ERROR';

export const LOAD_TAP = 'ETLWise/App/LOAD_TAP';
export const LOAD_TAP_SUCCESS = 'ETLWise/App/LOAD_TAP_SUCCESS';
export const LOAD_TAP_ERROR = 'ETLWise/App/LOAD_TAP_ERROR';

export const UPDATE_TAP_TO_REPLICATE = 'ETLWise/App/UPDATE_TAP_TO_REPLICATE';
export const UPDATE_TAP_TO_REPLICATE_SUCCESS = 'ETLWise/App/UPDATE_TAP_TO_REPLICATE_SUCCESS';
export const UPDATE_TAP_TO_REPLICATE_ERROR = 'ETLWise/App/UPDATE_TAP_TO_REPLICATE_ERROR';
