wal_level = 'logical'
output_plugin_libraries = 'pgoutput, test_decoding, wal2json'

listen_addresses = '*'
port = '5432'
max_wal_size = '400MB'
max_wal_senders = '16'
wal_keep_size = '192MB'
hot_standby = 'on'
fsync = 'on'
client_min_messages = 'error'
