"""Load generated connector credentials through an explicit filesystem seam."""

import json

from pathlib import Path


# pylint: disable=too-few-public-methods
class RuntimeConnectorConfigLoader:
    """Read source and target runtime JSON generated by PipelineWise."""

    def __init__(self, config_dir: str):
        self.config_dir = Path(config_dir)

    @staticmethod
    def _load(path: Path) -> dict:
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except FileNotFoundError as exc:
            raise ValueError(
                f"Generated connector config does not exist: {path}. "
                "Run pipelinewise import_config first."
            ) from exc

    def __call__(self, check: dict) -> tuple:
        """Return source and target connection dictionaries for one check."""
        target_dir = self.config_dir / check["target_id"]
        source_path = target_dir / check["tap_id"] / "config.json"
        target_path = target_dir / "config.json"
        return self._load(source_path), self._load(target_path)
