version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.4.8-jessie-browsers
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
            pip install pylint
            make test
            pylint tap_postgres -d missing-docstring,invalid-name,line-too-long,too-many-locals,too-few-public-methods,fixme,stop-iteration-return,duplicate-code,useless-import-alias
  test:
    docker:
      - image: circleci/python:3.4.8-jessie-browsers
    steps:
      - checkout
      - run: 'echo "Hello"'
