---
backend_database:
  enabled: true
  conn:
    driver: postgresql
    host: db_pipelinewise
    port: 5432
    username: pipelinewise
    password: secret
    dbname: pipelinewise

# Alert handlers send alerts on run failures
# Configure the certain alert handler if you want to send alerts
# on failures otherwise comment it
alert_handlers:
#  slack:
#    token: "slack-token"
#    channel: "#slack-channel"

#  victorops:
#    base_url: "https://alert.victorops.com/integrations/generic/.../alert/.../..."
#    routing_key: "victorops-routing-key"
