export const LOAD_INHERITABLE_CONFIG = 'TapInheritableConfig/LOAD_INHERITABLE_CONFIG';
export const LOAD_INHERITABLE_CONFIG_SUCCESS = 'TapInheritableConfig/LOAD_INHERITABLE_CONFIG_SUCCESS';
export const LOAD_INHERITABLE_CONFIG_ERROR = 'TapInheritableConfig/LOAD_INHERITABLE_CONFIG_ERROR';

export const SAVE_INHERITABLE_CONFIG = 'TapInheritableConfig/SAVE_INHERITABLE_CONFIG';
export const SAVE_INHERITABLE_CONFIG_SUCCESS = 'TapInheritableConfig/SAVE_INHERITABLE_CONFIG_SUCCESS';
export const SAVE_INHERITABLE_CONFIG_ERROR = 'TapInheritableConfig/SAVE_INHERITABLE_CONFIG_ERROR';

export const SET_SAVE_BUTTON_STATE = 'TapInheritableConfig/SET_SAVE_BUTTON_STATE';