version: '3.7'

services:
  mariadb_server1:
    container_name: "mariadb_server1"
    image: mariadb:10.6
    volumes:
      - ./dev/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-passwd
      MYSQL_DATABASE: tap_mysql_test
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: secret123passwd
    ports:
      - "3306:3306"
    command:
      --server-id=1
      --default-authentication-plugin=mysql_native_password
      --log-bin=mysql-bin
      --binlog-format=ROW
    networks:
      - mariadb-cluster

  mysql_server:
    container_name: 'mysql_server'
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: master1
      MYSQL_DATABASE: tap_mysql_test
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: secret123passwd
    volumes:
      - ./dev/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --server-id=1
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
      - --master-info-repository=TABLE
      - --relay-log-info-repository=TABLE
      - --binlog-checksum=NONE
      - --log-slave-updates=ON
      - --log-bin=binlog
      - --binlog-format=ROW
    networks:
      - mariadb-cluster

networks:
  mariadb-cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/24
