name: Publish documentation
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: doc-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          path: gh_doc_automation

      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10'

      - name: check structure
        run: ls -l gh_doc_automation

      - name: Check if doc has changed
        working-directory: gh_doc_automation
        id: check
        env:
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        continue-on-error: true
        run: ./scripts/ci_check_no_file_changes.sh doc

      - name: Publish doc
        if: steps.check.outcome == 'failure'
        working-directory: gh_doc_automation
        env:
          GH_NAME: ap-github                        # can be anything
          GH_EMAIL: ap-github@wise.com              # can be anything
          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}     # Comes from GH itself, available at runtime, not stored in secrets
        run: ./scripts/publish_docs.sh
