name: Publish documentation
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: gh_doc_automation

      - name: check structure
        run: ls -l gh_doc_automation

      - name: Check if doc has changed
        working-directory: gh_doc_automation
        id: check
        env:
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        continue-on-error: true
        run: ./gh_doc_automation/scripts/ci_check_no_file_changes.sh doc

      - name: Publish doc
        if: steps.check.outcome == 'failure'
        working-directory: gh_doc_automation
        env:
          GH_NAME: ap-github                        # can be anything
          GH_EMAIL: ap-github@wise.com              # can be anything
          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}     # Comes from GH itself, available at runtime, not stored in secrets
        run: ./gh_doc_automation/scripts/publish_docs.sh
