name: Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Checking out repo
        uses: actions/checkout@v2

      - name: Check if python changes are present
        id: check
        env:
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        continue-on-error: true
        run: ./scripts/ci_check_no_file_changes.sh python

      - name: Set up Python ${{ matrix.python-version }}
        if: steps.check.outcome == 'failure'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: steps.check.outcome == 'failure'
        run: |
          pip install -U pip setuptools wheel
          pip install -Ue .[test]

      - name: Run Unit tests
        if: steps.check.outcome == 'failure'
        run: |
          export PIPELINEWISE_HOME=$PWD
          pytest --cov=pipelinewise --cov-fail-under=72 -v tests/units
